"""create readings table

Revision ID: bb7feabf6399
Revises: 
Create Date: 2026-07-08 19:54:05.116035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7feabf6399'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('pulse', sa.Integer(), nullable=False),
    sa.Column('am_pm', sa.Text(), nullable=False),
    sa.Column('bp_category', sa.Text(), nullable=False),
    sa.Column('pulse_category', sa.Text(), nullable=False),
    sa.Column('map', sa.Numeric(precision=5, scale=1, asdecimal=False), nullable=False),
    sa.Column('pulse_pressure', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readings')),
    sa.UniqueConstraint('datetime', name=op.f('uq_readings_datetime'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    # ### end Alembic commands ###
